//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 08:10:32 PM EST 
//


package xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;&gt;ST_argument"&gt;
 *       &lt;attribute name="name" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="axisDimensions"/&gt;
 *             &lt;enumeration value="cameraDistance"/&gt;
 *             &lt;enumeration value="divisions"/&gt;
 *             &lt;enumeration value="divisionsX"/&gt;
 *             &lt;enumeration value="divisionsY"/&gt;
 *             &lt;enumeration value="functionScale"/&gt;
 *             &lt;enumeration value="majorRadius"/&gt;
 *             &lt;enumeration value="minorRadius"/&gt;
 *             &lt;enumeration value="plotHi"/&gt;
 *             &lt;enumeration value="plotLow"/&gt;
 *             &lt;enumeration value="rangeX"/&gt;
 *             &lt;enumeration value="rangeY"/&gt;
 *             &lt;enumeration value="xAxisHi"/&gt;
 *             &lt;enumeration value="xAxisLow"/&gt;
 *             &lt;enumeration value="xAxisTickUnit"/&gt;
 *             &lt;enumeration value="xPlotIncrement"/&gt;
 *             &lt;enumeration value="yAxisHi"/&gt;
 *             &lt;enumeration value="yAxisLow"/&gt;
 *             &lt;enumeration value="yAxisTickUnit"/&gt;
 *             &lt;enumeration value="zAxisHi"/&gt;
 *             &lt;enumeration value="zAxisLow"/&gt;
 *             &lt;enumeration value="zAxisTickUnit"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "argument")
public class Argument {

    @XmlValue
    protected BigDecimal value;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
